name = "HandyG"
uuid = "a852a908-0650-4c17-9fbe-e73c879a033a"
version = "0.1.0"

[deps]
HandyG_jll = "176cd8ec-bef4-5d25-a3d7-2797db4e996d"

[compat]
HandyG_jll = "0.2.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
